function showFact() {
    const facts = [
      "Octopuses have three hearts.",
      "Honey never spoils.",
      "Bananas are berries, but strawberries aren't.",
      "A group of flamingos is called a 'flamboyance'.",
      "The Eiffel Tower can be 15 cm taller during the summer.",
      "Sharks existed before trees.",
      "There are more stars in the universe than grains of sand on Earth.",
      "The moon has moonquakes.",
      "A bolt of lightning is five times hotter than the sun.",
      "Some turtles can breathe through their butts.",
      "You can't hum while holding your nose closed.",
      "Wombat poop is cube-shaped.",
      "Sloths can hold their breath longer than dolphins.",
      "Koalas have fingerprints.",
      "A cloud can weigh more than a million pounds.",
      "The heart of a blue whale is as big as a small car.",
      "An octopus has nine brains.",
      "There's a species of jellyfish that can live forever.",
      "Cows have best friends and get stressed when separated.",
      "A single strand of spaghetti is called a 'spaghetto'.",
      "Scotland's national animal is the unicorn.",
      "Cats can’t taste sweetness.",
      "The hashtag symbol is technically called an octothorpe.",
      "Your nose can remember 50,000 different scents.",
      "The first oranges weren’t orange.",
      "Sea otters hold hands while sleeping.",
      "A snail can sleep for three years.",
      "Some frogs freeze without dying.",
      "Butterflies taste with their feet.",
      "A day on Venus is longer than its year.",
      "Coca-Cola would be green if coloring weren’t added.",
      "An apple floats because it's 25% air.",
      "Avocados are fruit, not vegetables.",
      "Rabbits can’t vomit.",
      "The shortest war in history lasted 38 minutes.",
      "Pineapples take about two years to grow.",
      "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
      "Elephants can’t jump.",
      "Dolphins have names for each other.",
      "The inventor of the microwave appliance only received $2 for his discovery.",
      "Alaska is the westernmost, easternmost, and northernmost U.S. state.",
      "There's a basketball court on the top floor of the U.S. Supreme Court building—it's called the 'Highest Court in the Land'.",
      "Ketchup used to be sold as medicine.",
      "Slugs have four noses.",
      "The longest hiccuping spree lasted 68 years.",
      "Humans share 60% of their DNA with bananas.",
      "Antarctica has only one ATM.",
      "Some metals explode when in contact with water.",
      "A crocodile cannot stick its tongue out.",
      "There is a species of spider that can fly using electricity."
    ];

    const fact = facts[Math.floor(Math.random() * facts.length)];
    document.getElementById("fact").textContent = fact;
  }
